import {
  Armchair,
  ArrowRight,
  Bath,
  BedDouble,
  BedSingle,
  Box,
  Building,
  Building2,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChartColumn,
  CircleAlert,
  CircleCheck,
  Clock,
  CloudDownload,
  CookingPot,
  Copy,
  FilePen,
  FileText,
  FolderOpen,
  Gift,
  Globe,
  GripVertical,
  Headphones,
  Heart,
  House,
  Image as ImageIcon,
  Info,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  LoaderCircle,
  LockOpen,
  LogOut,
  MapPin,
  Maximize,
  Menu,
  Minus,
  MonitorPlay,
  MoreVertical,
  MoveHorizontal,
  MoveVertical,
  Pencil,
  Play,
  Plus,
  Rocket,
  Ruler,
  Scaling,
  Scissors,
  Search,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sofa,
  Sparkles,
  Target,
  Trash2,
  Trees,
  Trophy,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Warehouse,
  Waves,
  Wrench,
  X,
} from 'lucide-react'
import type { ComponentType, SVGProps } from 'react'

import { cn } from './cn'
import { Facebook, Google, Instagram, WhatsApp, YouTube } from './icons/brand'
import { FlagBR, FlagCN, FlagDE, FlagES, FlagFR, FlagIT, FlagJP, FlagUS } from './icons/flags'

// Único ponto que conhece a biblioteca de ícones: trocar de biblioteca muda só este arquivo.
const icons = {
  armchair: Armchair,
  'arrow-right': ArrowRight,
  bath: Bath,
  'bed-double': BedDouble,
  'bed-single': BedSingle,
  box: Box,
  building: Building,
  building2: Building2,
  car: Car,
  cart: ShoppingCart,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  chart: ChartColumn,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  clock: Clock,
  'cloud-download': CloudDownload,
  'cooking-pot': CookingPot,
  copy: Copy,
  dashboard: LayoutDashboard,
  'file-pen': FilePen,
  folder: FolderOpen,
  'file-text': FileText,
  gift: Gift,
  globe: Globe,
  grip: GripVertical,
  headphones: Headphones,
  heart: Heart,
  house: House,
  image: ImageIcon,
  info: Info,
  languages: Languages,
  'layout-grid': LayoutGrid,
  layers: Layers,
  loader: LoaderCircle,
  'lock-open': LockOpen,
  'log-out': LogOut,
  'map-pin': MapPin,
  maximize: Maximize,
  menu: Menu,
  minus: Minus,
  'monitor-play': MonitorPlay,
  'more-vertical': MoreVertical,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  rocket: Rocket,
  ruler: Ruler,
  scaling: Scaling,
  scissors: Scissors,
  search: Search,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  sofa: Sofa,
  sparkles: Sparkles,
  target: Target,
  trash: Trash2,
  trees: Trees,
  trophy: Trophy,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  video: Video,
  warehouse: Warehouse,
  waves: Waves,
  wrench: Wrench,
  close: X,
  facebook: Facebook,
  google: Google,
  instagram: Instagram,
  whatsapp: WhatsApp,
  youtube: YouTube,
  'flag-us': FlagUS,
  'flag-br': FlagBR,
  'flag-es': FlagES,
  'flag-fr': FlagFR,
  'flag-it': FlagIT,
  'flag-de': FlagDE,
  'flag-jp': FlagJP,
  'flag-cn': FlagCN,
} satisfies Record<string, ComponentType<SVGProps<SVGSVGElement>>>

export type IconName = keyof typeof icons

type IconProps = { name: IconName } & Omit<SVGProps<SVGSVGElement>, 'name'>

/** Ícone decorativo (aria-hidden). Tamanho padrão 20px; sobrescreva com `className="size-6"`. */
export function Icon({ name, className, ...props }: IconProps) {
  const Component = icons[name]
  return <Component aria-hidden="true" className={cn('size-5 shrink-0', className)} {...props} />
}
