import {
  Armchair,
  ArrowRight,
  Bath,
  BedDouble,
  BedSingle,
  Box,
  Building,
  Building2,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChartColumn,
  CircleAlert,
  CircleCheck,
  Clock,
  CloudDownload,
  CookingPot,
  Copy,
  FilePen,
  FileText,
  FolderOpen,
  Headphones,
  Heart,
  House,
  Image as ImageIcon,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  LoaderCircle,
  LogOut,
  MapPin,
  Maximize,
  Menu,
  Minus,
  MoreVertical,
  MoveHorizontal,
  MoveVertical,
  Pencil,
  Play,
  Plus,
  Ruler,
  Scaling,
  Scissors,
  Search,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  SlidersHorizontal,
  Sofa,
  Sparkles,
  Target,
  Trash2,
  Trees,
  Upload,
  User,
  Users,
  Utensils,
  Warehouse,
  Waves,
  X,
} from 'lucide-react'
import type { ComponentType, SVGProps } from 'react'

import { cn } from './cn'
import { Facebook, Google, Instagram, WhatsApp, YouTube } from './icons/brand'

// Único ponto que conhece a biblioteca de ícones: trocar de biblioteca muda só este arquivo.
const icons = {
  armchair: Armchair,
  'arrow-right': ArrowRight,
  bath: Bath,
  'bed-double': BedDouble,
  'bed-single': BedSingle,
  box: Box,
  building: Building,
  building2: Building2,
  car: Car,
  cart: ShoppingCart,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  chart: ChartColumn,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  clock: Clock,
  'cloud-download': CloudDownload,
  'cooking-pot': CookingPot,
  copy: Copy,
  dashboard: LayoutDashboard,
  'file-pen': FilePen,
  folder: FolderOpen,
  'file-text': FileText,
  headphones: Headphones,
  heart: Heart,
  house: House,
  image: ImageIcon,
  info: Info,
  'layout-grid': LayoutGrid,
  layers: Layers,
  loader: LoaderCircle,
  'log-out': LogOut,
  'map-pin': MapPin,
  maximize: Maximize,
  menu: Menu,
  minus: Minus,
  'more-vertical': MoreVertical,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  ruler: Ruler,
  scaling: Scaling,
  scissors: Scissors,
  search: Search,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  sliders: SlidersHorizontal,
  sofa: Sofa,
  sparkles: Sparkles,
  target: Target,
  trash: Trash2,
  trees: Trees,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  warehouse: Warehouse,
  waves: Waves,
  close: X,
  facebook: Facebook,
  google: Google,
  instagram: Instagram,
  whatsapp: WhatsApp,
  youtube: YouTube,
} satisfies Record<string, ComponentType<SVGProps<SVGSVGElement>>>

export type IconName = keyof typeof icons

type IconProps = { name: IconName } & Omit<SVGProps<SVGSVGElement>, 'name'>

/** Ícone decorativo (aria-hidden). Tamanho padrão 20px; sobrescreva com `className="size-6"`. */
export function Icon({ name, className, ...props }: IconProps) {
  const Component = icons[name]
  return <Component aria-hidden="true" className={cn('size-5 shrink-0', className)} {...props} />
}
